version: "3.7"
services:
  app:
    build:
      args:
        user: xrosoff
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: image-holidays-plans
    container_name: holidays-plans
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - holidays-plans
  db:
    image: mysql:8.0
    container_name: db-holidays-plans
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - holidays-plans
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-holidays-plans
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - holidays-plans
  nginx:
    image: nginx:alpine
    container_name: nginx-holidays-plans
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - holidays-plans
networks:
  holidays-plans:
    driver: bridge